title = "shopfront"
pluralizelisttitles = false
# baseURL is needed for successUrl/cancelUrl redirection from Stripe
baseURL = "https://shpfrnt.netlify.app"
[params]
	email = "hendry+shop@iki.fi"
	currency = "SGD" # ISO 4217
	stripe = "pk_test_1amuSFIBwCaicwoNGifewy4a"
[taxonomies]
	category = "categories"
	vendor = "vendors"
	tag = "tags"
