title = "FilmsByTom.com shop"
pluralizelisttitles = false
# baseURL is needed for successUrl/cancelUrl redirection from Stripe
baseURL = "https://filmsbytom.com/shop"
[params]
	email = "tom5@posteo.net"
	currency = "GBP" # ISO 4217
	stripe = "pk_test_"
[taxonomies]
	category = "categories"
	vendor = "vendors"
	tag = "tags"
[outputs]
	page = ["html","json"]
	section = ["html","json"]
	home = ["html","json"]
